package com.isesalud.model;

// Generated Feb 11, 2013 3:38:10 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import com.isesalud.support.components.BaseModel;

/**
 * Cita generated by Ing. Ari G. Sela M.
 */
@Entity
@Table(name = "cita")
public class Cita extends BaseModel{

	/**
	 * 
	 */
	private static final long serialVersionUID = -7318268764455653312L;
	private Long id;
	private Study study;
	private Statuscita statuscita;
	private Date date;
	private Date time;
	private Paciente paciente;
	private Date startDate;
	private Date endDate;
	private Boolean enviadosms;
	
	public Cita() {
		this.id = new Long(0L);
	}

	public Cita(Study study, Statuscita statuscita, Date date, Date time,
			Personal personal, Paciente paciente, Boolean enviadosms) {
		this.id = new Long(0L);
		this.study = study;
		this.statuscita = statuscita;
		this.date = date;
		this.time = time;
		this.paciente = paciente;
		this.enviadosms = enviadosms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "study", nullable = false)
	public Study getStudy() {
		return this.study;
	}


	public void setStudy(Study study) {
		this.study = study;
	}
	

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "statusCita", nullable = false)
	public Statuscita getStatuscita() {
		return this.statuscita;
	}

	public void setStatuscita(Statuscita statuscita) {
		this.statuscita = statuscita;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", nullable = false, length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name="enviadosms", nullable=false)
	@NotNull
	public Boolean getEnviadosms() {
		return enviadosms;
	}
	
	public void setEnviadosms(Boolean enviadosms) {
		this.enviadosms = enviadosms;
	}
	
	
	@ManyToOne(fetch=FetchType.EAGER, cascade = CascadeType.MERGE)
	@JoinColumn(name = "paciente", nullable = false)
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}
	
	@Transient
	public Date getStartDate() {
		return startDate;
	}
	
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	
	@Transient
	public Date getEndDate() {
		return endDate;
	}
	
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
}
