package com.isesalud.model;

// Generated Feb 11, 2013 3:38:10 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.isesalud.support.components.BaseModel;

/**
 * Cita generated by Ing. Ari G. Sela M.
 */
@Entity
@Table(name = "cita")
public class Cita extends BaseModel{

	/**
	 * 
	 */
	private static final long serialVersionUID = -7318268764455653312L;
	private Long id;
	private Tipocita tipocita;
	private Statuscita statuscita;
	private Date date;
	private Date time;
	private Personal personal;
	private Paciente paciente;

	public Cita() {
		this.id = new Long(0L);
	}

	public Cita(Tipocita tipocita, Statuscita statuscita, Date date, Date time,
			Personal personal, Paciente paciente) {
		this.id = new Long(0L);
		this.tipocita = tipocita;
		this.statuscita = statuscita;
		this.date = date;
		this.time = time;
		this.personal = personal;
		this.paciente = paciente;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipoCita", nullable = false)
	public Tipocita getTipocita() {
		return this.tipocita;
	}

	public void setTipocita(Tipocita tipocita) {
		this.tipocita = tipocita;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "statusCita", nullable = false)
	public Statuscita getStatuscita() {
		return this.statuscita;
	}

	public void setStatuscita(Statuscita statuscita) {
		this.statuscita = statuscita;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", nullable = false, length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "personal", nullable = false)
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "paciente", nullable = false)
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

}
