package com.isesalud.model;

// Generated Feb 11, 2013 3:38:10 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.isesalud.support.components.BaseModel;

/**
 * Tipocita generated by Ing. Ari G. Sela M.
 */
@Entity
@Table(name = "tipocita")
public class Tipocita extends BaseModel {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4648741653714278844L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;
	
	@Column(name = "description", nullable = false, length = 100)
	private String description;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipocita")
	private List<TipoEstudioCita> tipoEstudioCitas = new ArrayList<TipoEstudioCita>(0);
	
	
	public Tipocita() {
	this.id = new Long(0L);
	}

	public Tipocita(String description) {
		this.id = new Long(0L);
		this.description = description;
	}

		
	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return this.id;
	}
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	public List<TipoEstudioCita> getTipoEstudioCitas() {
		return tipoEstudioCitas;
	}

	public void setTipoEstudioCitas(List<TipoEstudioCita> tipoEstudioCitas) {
		this.tipoEstudioCitas = tipoEstudioCitas;
	}
	
}
