package com.isesalud.model;

// Generated Feb 11, 2013 3:38:10 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipocita generated by Ing. Ari G. Sela M.
 */
@Entity
@Table(name = "tipocita")
public class Tipocita extends BaseModel {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4648741653714278844L;
	private Long id;
	private String description;
	private List<Cita> citas = new ArrayList<Cita>(0);

	public Tipocita() {
	}

	public Tipocita(String description) {
		this.description = description;
	}

	public Tipocita(String description, List<Cita> citas) {
		this.description = description;
		this.citas = citas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipocita")
	public List<Cita> getCitas() {
		return this.citas;
	}

	public void setCitas(List<Cita> citas) {
		this.citas = citas;
	}

}
